spring.application.name=RoomMateX

# ===============================
# Server
# ===============================
server.port=8081

# ===============================
# PostgreSQL Database
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/roommatex
spring.datasource.username=postgres
spring.datasource.password=kanak

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT
# ===============================
jwt.secret=roommate_secret_key_roommate_secret_key_123456
jwt.expiration=86400000

razorpay.key=rzp_test_xxxxxx
razorpay.secret=xxxxxxxx

# ===============================
# Redis (optional ? only if using)
# ===============================
#spring.cache.type=redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

# ===============================
# Logging (optional)
# ===============================
logging.level.org.springframework.security=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ksao180205@gmail.com
spring.mail.password=lgcldcqytmpfnvf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com



razorpay.webhook.secret=whsec_xxxxx
